### ISSUE TITLE
README Shows Incomplete Import Statement

### ISSUE THREAD

**Issue by engineerjoe440** [codemation/pydbantic#27]
By my reading, it looks like [this example](https://github.com/codemation/pydbantic/blob/main/README.md#basic-usage---connecting-a-database-to-models) shows an incomplete import statement. The statement does not import *all* of the models required to create the database. (I think :stuck_out_tongue_closed_eyes: )

### Present documentation
```python
import asyncio
from pydbantic import Database
from models import Employee ### <---- Missing additional model imports here...?

async def main():
    db = await Database.create(
        'sqlite:///test.db',
        tables=[
            Employee,
            EmployeeInfo,
            Positions,
            Department
        ]
    )

if __name__ == '__main__':
    asyncio.run(main())
```

### Suggested Documentation

```python
import asyncio
from pydbantic import Database
from models import Employee, EmployeeInfo, Positions, Department

async def main():
    db = await Database.create(
        'sqlite:///test.db',
        tables=[
            Employee,
            EmployeeInfo,
            Positions,
            Department
        ]
    )

if __name__ == '__main__':
    asyncio.run(main())
```

**Comment by engineerjoe440** [comment]
On another note.... THIS PROJECT LOOKS AMAZING! Thank you so much for your work on this, I'm terrified of databases, and this makes them look so approachable, I'm excited to play with it!

**Comment by codemation** [comment]
Hey @engineerjoe440 , thanks for opening the issue, I will try to cover this in my next PR. Feel free in the future to also fork / fix / create your own PR, all contributions are welcome.

**Comment by engineerjoe440** [comment]
Hi @codemation! I'm so excited to hear you're open to PR's! I'll go ahead and fork, make those updates and open one. Thanks again for this outstanding work. I can't wait to find an excuse to start using it!

**Comment by engineerjoe440** [comment]
Thanks again, @codemation!
