### ISSUE TITLE
bump databases version to 0.6.0 and pydantic to 1.9.1

### ISSUE THREAD

**Issue by KKP4** [codemation/pydbantic#33]
It's not possible to use easyauth with the latest encoding/databases version 0.6.0 since pydbantic depends on version 0.5.3.
Is it possible to bump the version or are there any backwards compatibility issues?

In addition to databases consider upgrading pydantic to 1.9.1 - latest.

**Comment by codemation** [comment]
Hey @KKP4  thanks for raising an issue on this, I will run through the tests on the latest releases and see if there are any issues that prevent a bump in pinned versions.

**Comment by codemation** [comment]
@KKP4 - everything passing in latest releases - this is fixed in release version 0.0.24

**Comment by eudoxos** [comment]
fix also setup.py in #36
