### ISSUE TITLE
pydantic version clash 1.10

### ISSUE THREAD

**Issue by ttamg** [codemation/pydbantic#42]
Hi there.

Pydantic is now on 1.10.x

The requirements are pinned in `requirements.txt` to pydantic 1.9.1.   So installing into a project with pydantic 1.10 causes a dependency clash and failure.

Do you think you can updated requirements please?

Thanks

**Comment by codemation** [comment]
Hey @ttamg , good suggestion, created https://github.com/codemation/pydbantic/pull/43 to allow 1.9.1 + versions of pydantic. Pending tests passing, will be included in next release.

**Comment by codemation** [comment]
https://github.com/codemation/pydbantic/releases/tag/0.0.30

**Comment by ttamg** [comment]
Awesome.  Thanks.

**Comment by codemation** [comment]
Scratch that, 0.0.31, typo in setup.py
