### ISSUE TITLE
Warning database init ready

### ISSUE THREAD

**Issue by Creadeyh** [codemation/pydbantic#54]
Hi,

I'm running pydbantic without alembic `await Database.create("sqlite_string", tables=[Project, Comment])`.
I'm getting `WARNING database init - ready` when I run the app.
Digging in pydbantic's code, it's coming from database.py:592, it seems like normal operation and my app is working perfectly.

Unless I missed something, shouldn't this log be changed to INFO or DEBUG ?
Thanks

**Comment by codemation** [comment]
Hello @Creadeyh , indeed this is meant as more of an INFO message. Happy to hear everything else is working well. Will update within next release
