### ISSUE TITLE
Fails to run with pydantic >= 2

### ISSUE THREAD

**Issue by jameslewellyn** [codemation/pydbantic#60]
When using the newly released pydantic 2, pydbantic fails with the following error (I tried both in a simple example from the tutorial and using the `make test` functionality and got the same result):
- AttributeError: 'Field' object has no attribute 'type_'

Switching to a pydantic < 2.0 fixes the issue.

One option is changing setup.py to include and upper bound on pydantic version until v2 is supported:
- "pydantic>=1.9.1,<2",

**Comment by FluffyDietEngine** [comment]
@jameslewellyn Good suggestion. 

Opened [PR](https://github.com/codemation/pydbantic/pull/63)

**Comment by codemation** [comment]
@jameslewellyn @FluffyDietEngine thanks for your contributions, pending PR tests passing, we can push this fix in ASAP.

**Comment by codemation** [comment]
@FluffyDietEngine  your PR encountered test issues, but I went ahead and fixed in the next release: https://github.com/codemation/pydbantic/releases/tag/0.0.42
